# Germany - Regional Services
name = "global-healthchecks-de"
main = "src/worker.ts"
compatibility_date = "2025-02-07"
compatibility_flags = ["nodejs_compat"]
account_id = "e7452b39fc737014144e3b3fca412900"

assets = { directory = "dist", binding = "ASSETS" }
workers_dev = false

# Regional Services: Execute within Germany boundary
[placement]
mode = "smart"

[env.production]
route = { pattern = "de.healthchecks.ross.gg/*", zone_name = "ross.gg" }
placement = { mode = "smart", hint = "de" }
