# Oceania - Sydney region
name = "global-healthchecks-oc"
main = "src/worker.ts"
compatibility_date = "2025-02-07"
compatibility_flags = ["nodejs_compat"]

assets = { directory = "dist", binding = "ASSETS" }
workers_dev = false

[env.production]
route = { pattern = "oc.healthchecks.ross.gg/*", zone_name = "ross.gg" }
