# Japan - Regional Services
name = "global-healthchecks-jp"
main = "src/worker.ts"
compatibility_date = "2025-02-07"
compatibility_flags = ["nodejs_compat"]
account_id = "e7452b39fc737014144e3b3fca412900"

assets = { directory = "dist", binding = "ASSETS" }
workers_dev = false

# Regional Services: Execute within Japan boundary
[placement]
mode = "regional"

[env.production]
route = { pattern = "jp.healthchecks.ross.gg/*", zone_name = "ross.gg" }
placement = { mode = "regional", region = "jp" }
