# West Europe - London region
name = "global-healthchecks-weur"
main = "src/worker.ts"
compatibility_date = "2025-02-07"
compatibility_flags = ["nodejs_compat"]
account_id = "e7452b39fc737014144e3b3fca412900"

assets = { directory = "dist", binding = "ASSETS" }
workers_dev = false

# Placement hint: Execute in West Europe region
[placement]
mode = "smart"

[env.production]
route = { pattern = "weur.healthchecks.ross.gg/*", zone_name = "ross.gg" }
placement = { mode = "smart", hint = "weur" }
